// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALNZ8DMsmKJZ2cs5xe-nlUDFdxlvUwFj8',
    appId: '1:95233047869:web:634731fe2b92b19cb8d954',
    messagingSenderId: '95233047869',
    projectId: 'attendance-maintainance',
    authDomain: 'attendance-maintainance.firebaseapp.com',
    storageBucket: 'attendance-maintainance.firebasestorage.app',
    measurementId: 'G-PRFRV6NB1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWHTEC7P8IfUqWMaDIqBAmw3brU94wFM',
    appId: '1:95233047869:android:d7010a19dd5020a6b8d954',
    messagingSenderId: '95233047869',
    projectId: 'attendance-maintainance',
    storageBucket: 'attendance-maintainance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhqIuvSPyUrb3EiQi0qlDFXNaf3ACSC0',
    appId: '1:95233047869:ios:e9431274bd34332bb8d954',
    messagingSenderId: '95233047869',
    projectId: 'attendance-maintainance',
    storageBucket: 'attendance-maintainance.firebasestorage.app',
    iosClientId: '95233047869-e4tt8fsap3mm0gqropqjgrmgtkvggbh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceMaintainance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhqIuvSPyUrb3EiQi0qlDFXNaf3ACSC0',
    appId: '1:95233047869:ios:e9431274bd34332bb8d954',
    messagingSenderId: '95233047869',
    projectId: 'attendance-maintainance',
    storageBucket: 'attendance-maintainance.firebasestorage.app',
    iosClientId: '95233047869-e4tt8fsap3mm0gqropqjgrmgtkvggbh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceMaintainance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALNZ8DMsmKJZ2cs5xe-nlUDFdxlvUwFj8',
    appId: '1:95233047869:web:ec90b14a69df2f37b8d954',
    messagingSenderId: '95233047869',
    projectId: 'attendance-maintainance',
    authDomain: 'attendance-maintainance.firebaseapp.com',
    storageBucket: 'attendance-maintainance.firebasestorage.app',
    measurementId: 'G-JVJL9QG198',
  );
}
